<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 12 Logistic Regression | Analysis of Household Education Survey Data using R</title>
  <meta name="description" content="Chapter 12 Logistic Regression | Analysis of Household Education Survey Data using R" />
  <meta name="generator" content="bookdown 0.46 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 12 Logistic Regression | Analysis of Household Education Survey Data using R" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 12 Logistic Regression | Analysis of Household Education Survey Data using R" />
  
  
  

<meta name="author" content="African Foundational Learning Data Hub at DataFirst" />


<meta name="date" content="2026-06-13" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="multiple-linear-regression.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Analysis of Household Education Survey Data using R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#what-you-will-learn"><i class="fa fa-check"></i><b>1.1</b> What you will learn</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="index.html"><a href="index.html#part-i---getting-started-in-r-chapters-2-3"><i class="fa fa-check"></i><b>1.1.1</b> Part I - Getting started in R (Chapters 2-3)</a></li>
<li class="chapter" data-level="1.1.2" data-path="index.html"><a href="index.html#part-ii---exploring-and-preparing-data-chapters-4-6"><i class="fa fa-check"></i><b>1.1.2</b> Part II - Exploring and preparing data (Chapters 4-6)</a></li>
<li class="chapter" data-level="1.1.3" data-path="index.html"><a href="index.html#part-iii---describing-and-modelling-learning-outcomes-chapters-7---12"><i class="fa fa-check"></i><b>1.1.3</b> Part III - Describing and modelling learning outcomes (Chapters 7 - 12)</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#what-you-need"><i class="fa fa-check"></i><b>1.2</b> What you need</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html"><i class="fa fa-check"></i><b>2</b> Getting Started with R</a>
<ul>
<li class="chapter" data-level="2.1" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#rstudio-interface"><i class="fa fa-check"></i><b>2.1</b> RStudio interface</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#source-editor"><i class="fa fa-check"></i><b>2.1.1</b> Source/ Editor</a></li>
<li class="chapter" data-level="2.1.2" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#example-running-a-line-of-code-in-the-editor"><i class="fa fa-check"></i><b>2.1.2</b> Example: Running a line of code in the Editor</a></li>
<li class="chapter" data-level="2.1.3" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#console"><i class="fa fa-check"></i><b>2.1.3</b> Console</a></li>
<li class="chapter" data-level="2.1.4" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#environment-tab"><i class="fa fa-check"></i><b>2.1.4</b> Environment Tab</a></li>
<li class="chapter" data-level="2.1.5" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#history-tab"><i class="fa fa-check"></i><b>2.1.5</b> History Tab</a></li>
<li class="chapter" data-level="2.1.6" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#files-tab"><i class="fa fa-check"></i><b>2.1.6</b> Files Tab</a></li>
<li class="chapter" data-level="2.1.7" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#plots-tab"><i class="fa fa-check"></i><b>2.1.7</b> Plots Tab</a></li>
<li class="chapter" data-level="2.1.8" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#packages-tab"><i class="fa fa-check"></i><b>2.1.8</b> Packages Tab</a></li>
<li class="chapter" data-level="2.1.9" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#help-tab"><i class="fa fa-check"></i><b>2.1.9</b> Help Tab</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#organize-your-r-session"><i class="fa fa-check"></i><b>2.2</b> Organize your R session</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#working-directory-where-r-looks-for-your-files"><i class="fa fa-check"></i><b>2.2.1</b> Working Directory: Where R Looks for Your Files</a></li>
<li class="chapter" data-level="2.2.2" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#installing-and-loading-packages-libraries"><i class="fa fa-check"></i><b>2.2.2</b> Installing and Loading Packages (Libraries)</a></li>
<li class="chapter" data-level="2.2.3" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#comments-in-r"><i class="fa fa-check"></i><b>2.2.3</b> Comments in R</a></li>
<li class="chapter" data-level="2.2.4" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#common-mistakes-and-quick-fixes"><i class="fa fa-check"></i><b>2.2.4</b> Common mistakes and quick fixes</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#getting-help"><i class="fa fa-check"></i><b>2.3</b> Getting help</a></li>
<li class="chapter" data-level="2.4" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#operators-in-r"><i class="fa fa-check"></i><b>2.4</b> Operators in R</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#basic-arithmetic-operators"><i class="fa fa-check"></i><b>2.4.1</b> Basic arithmetic operators</a></li>
<li class="chapter" data-level="2.4.2" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#assignment-operator"><i class="fa fa-check"></i><b>2.4.2</b> Assignment operator</a></li>
<li class="chapter" data-level="2.4.3" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#sequence-operator"><i class="fa fa-check"></i><b>2.4.3</b> Sequence operator</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#objects-in-r"><i class="fa fa-check"></i><b>2.5</b> Objects in R</a></li>
<li class="chapter" data-level="2.6" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#managing-the-workspace"><i class="fa fa-check"></i><b>2.6</b> Managing the workspace</a></li>
<li class="chapter" data-level="2.7" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#some-language-features"><i class="fa fa-check"></i><b>2.7</b> Some language features</a></li>
<li class="chapter" data-level="2.8" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#test-your-knowledge"><i class="fa fa-check"></i><b>2.8</b> Test your knowledge</a></li>
<li class="chapter" data-level="2.9" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#session-information"><i class="fa fa-check"></i><b>2.9</b> Session information</a></li>
<li class="chapter" data-level="2.10" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#acknowledgements"><i class="fa fa-check"></i><b>2.10</b> Acknowledgements</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="r-basics.html"><a href="r-basics.html"><i class="fa fa-check"></i><b>3</b> R Basics</a>
<ul>
<li class="chapter" data-level="3.1" data-path="r-basics.html"><a href="r-basics.html#scalar-arithmetic"><i class="fa fa-check"></i><b>3.1</b> Scalar Arithmetic</a></li>
<li class="chapter" data-level="3.2" data-path="r-basics.html"><a href="r-basics.html#vector-arithmetic"><i class="fa fa-check"></i><b>3.2</b> Vector Arithmetic</a></li>
<li class="chapter" data-level="3.3" data-path="r-basics.html"><a href="r-basics.html#matrices-and-matrix-functions"><i class="fa fa-check"></i><b>3.3</b> Matrices and Matrix Functions</a></li>
<li class="chapter" data-level="3.4" data-path="r-basics.html"><a href="r-basics.html#data-frame"><i class="fa fa-check"></i><b>3.4</b> Data Frame</a></li>
<li class="chapter" data-level="3.5" data-path="r-basics.html"><a href="r-basics.html#missing-values"><i class="fa fa-check"></i><b>3.5</b> Missing Values</a></li>
<li class="chapter" data-level="3.6" data-path="r-basics.html"><a href="r-basics.html#control-flow"><i class="fa fa-check"></i><b>3.6</b> Control Flow</a>
<ul>
<li class="chapter" data-level="3.6.1" data-path="r-basics.html"><a href="r-basics.html#logical-operators"><i class="fa fa-check"></i><b>3.6.1</b> Logical Operators</a></li>
<li class="chapter" data-level="3.6.2" data-path="r-basics.html"><a href="r-basics.html#if-statement"><i class="fa fa-check"></i><b>3.6.2</b> <code>if</code> statement</a></li>
<li class="chapter" data-level="3.6.3" data-path="r-basics.html"><a href="r-basics.html#for-loop"><i class="fa fa-check"></i><b>3.6.3</b> <code>for</code> loop</a></li>
<li class="chapter" data-level="3.6.4" data-path="r-basics.html"><a href="r-basics.html#for-loop-with-an-if-statement"><i class="fa fa-check"></i><b>3.6.4</b> <code>for</code> loop with an <code>if</code> statement</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="intro-to-ggplot.html"><a href="intro-to-ggplot.html"><i class="fa fa-check"></i><b>4</b> Intro to ggplot</a>
<ul>
<li class="chapter" data-level="4.1" data-path="intro-to-ggplot.html"><a href="intro-to-ggplot.html#what-is-ggplot2"><i class="fa fa-check"></i><b>4.1</b> What is ggplot2?</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="intro-to-ggplot.html"><a href="intro-to-ggplot.html#optional-grammar-of-graphics-background"><i class="fa fa-check"></i><b>4.1.1</b> Optional: Grammar of Graphics (background)</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="intro-to-ggplot.html"><a href="intro-to-ggplot.html#the-main-pieces-of-ggplot2"><i class="fa fa-check"></i><b>4.2</b> The main pieces of ggplot2</a></li>
<li class="chapter" data-level="4.3" data-path="intro-to-ggplot.html"><a href="intro-to-ggplot.html#building-your-first-plot-data-aes-geom"><i class="fa fa-check"></i><b>4.3</b> Building your first plot: data → aes → geom</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="intro-to-ggplot.html"><a href="intro-to-ggplot.html#step-1-choose-the-data"><i class="fa fa-check"></i><b>4.3.1</b> Step 1: Choose the data</a></li>
<li class="chapter" data-level="4.3.2" data-path="intro-to-ggplot.html"><a href="intro-to-ggplot.html#step-2-map-variables-with-aes"><i class="fa fa-check"></i><b>4.3.2</b> Step 2: Map variables with <code>aes()</code></a></li>
<li class="chapter" data-level="4.3.3" data-path="intro-to-ggplot.html"><a href="intro-to-ggplot.html#step-3-add-a-geometry-with-geom_point"><i class="fa fa-check"></i><b>4.3.3</b> Step 3: Add a geometry with <code>geom_point()</code></a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="intro-to-ggplot.html"><a href="intro-to-ggplot.html#aesthetics-colour-shape-size"><i class="fa fa-check"></i><b>4.4</b> Aesthetics: colour, shape, size</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="intro-to-ggplot.html"><a href="intro-to-ggplot.html#mapping-shape-to-a-variable"><i class="fa fa-check"></i><b>4.4.1</b> Mapping shape to a variable</a></li>
<li class="chapter" data-level="4.4.2" data-path="intro-to-ggplot.html"><a href="intro-to-ggplot.html#mapping-colour-to-a-variable"><i class="fa fa-check"></i><b>4.4.2</b> Mapping colour to a variable</a></li>
<li class="chapter" data-level="4.4.3" data-path="intro-to-ggplot.html"><a href="intro-to-ggplot.html#mapping-size-to-a-variable-e.g.-age"><i class="fa fa-check"></i><b>4.4.3</b> Mapping size to a variable (e.g., age)</a></li>
<li class="chapter" data-level="4.4.4" data-path="intro-to-ggplot.html"><a href="intro-to-ggplot.html#using-a-categorical-variable"><i class="fa fa-check"></i><b>4.4.4</b> Using a categorical variable</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="intro-to-ggplot.html"><a href="intro-to-ggplot.html#aesthetic-mapping-vs-fixed-settings-some-nuance"><i class="fa fa-check"></i><b>4.5</b> Aesthetic mapping vs fixed settings (some nuance)</a></li>
<li class="chapter" data-level="4.6" data-path="intro-to-ggplot.html"><a href="intro-to-ggplot.html#small-polish-labels-and-a-simple-theme"><i class="fa fa-check"></i><b>4.6</b> Small polish: labels and a simple theme</a></li>
<li class="chapter" data-level="4.7" data-path="intro-to-ggplot.html"><a href="intro-to-ggplot.html#practice-test-your-knowledge-with-mpg"><i class="fa fa-check"></i><b>4.7</b> Practice: Test your knowledge with <code>mpg</code></a></li>
<li class="chapter" data-level="4.8" data-path="intro-to-ggplot.html"><a href="intro-to-ggplot.html#saving-plots-to-files-with-ggsave"><i class="fa fa-check"></i><b>4.8</b> Saving plots to files with <code>ggsave()</code></a></li>
<li class="chapter" data-level="4.9" data-path="intro-to-ggplot.html"><a href="intro-to-ggplot.html#useful-resources"><i class="fa fa-check"></i><b>4.9</b> Useful resources</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="intro-to-data-wrangling-with-tidyverse.html"><a href="intro-to-data-wrangling-with-tidyverse.html"><i class="fa fa-check"></i><b>5</b> Intro to data wrangling with tidyverse</a>
<ul>
<li class="chapter" data-level="5.1" data-path="intro-to-data-wrangling-with-tidyverse.html"><a href="intro-to-data-wrangling-with-tidyverse.html#what-makes-the-tidyverse-special"><i class="fa fa-check"></i><b>5.1</b> What makes the tidyverse special?</a></li>
<li class="chapter" data-level="5.2" data-path="intro-to-data-wrangling-with-tidyverse.html"><a href="intro-to-data-wrangling-with-tidyverse.html#why-learn-dplyr-first"><i class="fa fa-check"></i><b>5.2</b> Why learn dplyr first?</a></li>
<li class="chapter" data-level="5.3" data-path="intro-to-data-wrangling-with-tidyverse.html"><a href="intro-to-data-wrangling-with-tidyverse.html#data-wrangling-with-dplyr"><i class="fa fa-check"></i><b>5.3</b> Data wrangling with dplyr</a></li>
<li class="chapter" data-level="5.4" data-path="intro-to-data-wrangling-with-tidyverse.html"><a href="intro-to-data-wrangling-with-tidyverse.html#import-data"><i class="fa fa-check"></i><b>5.4</b> Import Data</a></li>
<li class="chapter" data-level="5.5" data-path="intro-to-data-wrangling-with-tidyverse.html"><a href="intro-to-data-wrangling-with-tidyverse.html#working-with-tibbles"><i class="fa fa-check"></i><b>5.5</b> Working with Tibbles</a></li>
<li class="chapter" data-level="5.6" data-path="intro-to-data-wrangling-with-tidyverse.html"><a href="intro-to-data-wrangling-with-tidyverse.html#the-five-key-dplyr-verbs"><i class="fa fa-check"></i><b>5.6</b> The Five Key dplyr Verbs</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="intro-to-data-wrangling-with-tidyverse.html"><a href="intro-to-data-wrangling-with-tidyverse.html#filtering-rows-with-filter"><i class="fa fa-check"></i><b>5.6.1</b> Filtering rows with <code>filter()</code></a></li>
<li class="chapter" data-level="5.6.2" data-path="intro-to-data-wrangling-with-tidyverse.html"><a href="intro-to-data-wrangling-with-tidyverse.html#introducing-the-pipe"><i class="fa fa-check"></i><b>5.6.2</b> Introducing the pipe</a></li>
<li class="chapter" data-level="5.6.3" data-path="intro-to-data-wrangling-with-tidyverse.html"><a href="intro-to-data-wrangling-with-tidyverse.html#arranging-rows-with-arrange"><i class="fa fa-check"></i><b>5.6.3</b> Arranging rows with <code>arrange()</code></a></li>
<li class="chapter" data-level="5.6.4" data-path="intro-to-data-wrangling-with-tidyverse.html"><a href="intro-to-data-wrangling-with-tidyverse.html#selecting-columns-with-select"><i class="fa fa-check"></i><b>5.6.4</b> Selecting columns with <code>select()</code></a></li>
<li class="chapter" data-level="5.6.5" data-path="intro-to-data-wrangling-with-tidyverse.html"><a href="intro-to-data-wrangling-with-tidyverse.html#adding-new-variables-with-mutate"><i class="fa fa-check"></i><b>5.6.5</b> Adding new variables with <code>mutate()</code></a></li>
<li class="chapter" data-level="5.6.6" data-path="intro-to-data-wrangling-with-tidyverse.html"><a href="intro-to-data-wrangling-with-tidyverse.html#aggregating-over-rows-with-summarise"><i class="fa fa-check"></i><b>5.6.6</b> Aggregating over rows with <code>summarise()</code></a></li>
<li class="chapter" data-level="5.6.7" data-path="intro-to-data-wrangling-with-tidyverse.html"><a href="intro-to-data-wrangling-with-tidyverse.html#sources-and-references"><i class="fa fa-check"></i><b>5.6.7</b> Sources and references</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>I Analysis</b></span></li>
<li class="chapter" data-level="6" data-path="getting-started.html"><a href="getting-started.html"><i class="fa fa-check"></i><b>6</b> Getting Started</a>
<ul>
<li class="chapter" data-level="6.1" data-path="getting-started.html"><a href="getting-started.html#introduction-1"><i class="fa fa-check"></i><b>6.1</b> Introduction</a></li>
<li class="chapter" data-level="6.2" data-path="getting-started.html"><a href="getting-started.html#setup"><i class="fa fa-check"></i><b>6.2</b> Setup</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="getting-started.html"><a href="getting-started.html#packages"><i class="fa fa-check"></i><b>6.2.1</b> Packages</a></li>
<li class="chapter" data-level="6.2.2" data-path="getting-started.html"><a href="getting-started.html#ican-icar-2025-data"><i class="fa fa-check"></i><b>6.2.2</b> ICAN-ICAR 2025 Data</a></li>
<li class="chapter" data-level="6.2.3" data-path="getting-started.html"><a href="getting-started.html#survey-design-object"><i class="fa fa-check"></i><b>6.2.3</b> Survey Design Object</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="getting-started.html"><a href="getting-started.html#survey-analysis-process"><i class="fa fa-check"></i><b>6.3</b> Survey Analysis Process</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="understanding-distributions.html"><a href="understanding-distributions.html"><i class="fa fa-check"></i><b>7</b> Understanding distributions</a>
<ul>
<li class="chapter" data-level="7.1" data-path="understanding-distributions.html"><a href="understanding-distributions.html#getting-oriented-to-the-data"><i class="fa fa-check"></i><b>7.1</b> Getting oriented to the data</a></li>
<li class="chapter" data-level="7.2" data-path="understanding-distributions.html"><a href="understanding-distributions.html#levels-of-measurement"><i class="fa fa-check"></i><b>7.2</b> Levels of measurement</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="understanding-distributions.html"><a href="understanding-distributions.html#continuous-level"><i class="fa fa-check"></i><b>7.2.1</b> Continuous level</a></li>
<li class="chapter" data-level="7.2.2" data-path="understanding-distributions.html"><a href="understanding-distributions.html#ordinal-level"><i class="fa fa-check"></i><b>7.2.2</b> Ordinal level</a></li>
<li class="chapter" data-level="7.2.3" data-path="understanding-distributions.html"><a href="understanding-distributions.html#categorical-level"><i class="fa fa-check"></i><b>7.2.3</b> Categorical level</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="understanding-distributions.html"><a href="understanding-distributions.html#weighted-summaries-using-the-survey-design"><i class="fa fa-check"></i><b>7.3</b> Weighted summaries using the survey design</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="understanding-distributions.html"><a href="understanding-distributions.html#weighted-proportions-and-means"><i class="fa fa-check"></i><b>7.3.1</b> Weighted proportions and means</a></li>
<li class="chapter" data-level="7.3.2" data-path="understanding-distributions.html"><a href="understanding-distributions.html#weighted-frequency-tables"><i class="fa fa-check"></i><b>7.3.2</b> Weighted frequency tables</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="understanding-distributions.html"><a href="understanding-distributions.html#household-level-variables-in-a-child-level-file"><i class="fa fa-check"></i><b>7.4</b> Household-level variables in a child-level file</a></li>
<li class="chapter" data-level="7.5" data-path="understanding-distributions.html"><a href="understanding-distributions.html#missing-data-and-skip-patterns"><i class="fa fa-check"></i><b>7.5</b> Missing data and skip patterns</a></li>
<li class="chapter" data-level="7.6" data-path="understanding-distributions.html"><a href="understanding-distributions.html#practice-exercise"><i class="fa fa-check"></i><b>7.6</b> Practice Exercise</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="central-tendency-and-dispersion.html"><a href="central-tendency-and-dispersion.html"><i class="fa fa-check"></i><b>8</b> Central Tendency and Dispersion</a>
<ul>
<li class="chapter" data-level="8.1" data-path="central-tendency-and-dispersion.html"><a href="central-tendency-and-dispersion.html#central-tendency"><i class="fa fa-check"></i><b>8.1</b> Central tendency</a></li>
<li class="chapter" data-level="8.2" data-path="central-tendency-and-dispersion.html"><a href="central-tendency-and-dispersion.html#dispersion"><i class="fa fa-check"></i><b>8.2</b> Dispersion</a></li>
<li class="chapter" data-level="8.3" data-path="central-tendency-and-dispersion.html"><a href="central-tendency-and-dispersion.html#weighted-design-correct-summaries"><i class="fa fa-check"></i><b>8.3</b> Weighted, design-correct summaries</a></li>
<li class="chapter" data-level="8.4" data-path="central-tendency-and-dispersion.html"><a href="central-tendency-and-dispersion.html#outliers-and-the-unit-of-analysis"><i class="fa fa-check"></i><b>8.4</b> Outliers and the unit of analysis</a></li>
<li class="chapter" data-level="8.5" data-path="central-tendency-and-dispersion.html"><a href="central-tendency-and-dispersion.html#practice-exercises"><i class="fa fa-check"></i><b>8.5</b> Practice exercises</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="bivariate-analysis.html"><a href="bivariate-analysis.html"><i class="fa fa-check"></i><b>9</b> Bivariate Analysis</a>
<ul>
<li class="chapter" data-level="9.1" data-path="bivariate-analysis.html"><a href="bivariate-analysis.html#choosing-the-right-bivariate-tool"><i class="fa fa-check"></i><b>9.1</b> Choosing the right bivariate tool</a></li>
<li class="chapter" data-level="9.2" data-path="bivariate-analysis.html"><a href="bivariate-analysis.html#categorical-categorical-cross-tabulations"><i class="fa fa-check"></i><b>9.2</b> Categorical × categorical: cross-tabulations</a></li>
<li class="chapter" data-level="9.3" data-path="bivariate-analysis.html"><a href="bivariate-analysis.html#continuous-categorical-comparing-group-means"><i class="fa fa-check"></i><b>9.3</b> Continuous × categorical: comparing group means</a></li>
<li class="chapter" data-level="9.4" data-path="bivariate-analysis.html"><a href="bivariate-analysis.html#continuous-continuous-scatterplots-and-trends"><i class="fa fa-check"></i><b>9.4</b> Continuous × continuous: scatterplots and trends</a></li>
<li class="chapter" data-level="9.5" data-path="bivariate-analysis.html"><a href="bivariate-analysis.html#testing-association-with-chi-squared-tests"><i class="fa fa-check"></i><b>9.5</b> Testing association with chi-squared tests</a></li>
<li class="chapter" data-level="9.6" data-path="bivariate-analysis.html"><a href="bivariate-analysis.html#practice-exercises-1"><i class="fa fa-check"></i><b>9.6</b> Practice exercises</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html"><i class="fa fa-check"></i><b>10</b> Simple Linear Regression</a>
<ul>
<li class="chapter" data-level="10.1" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#preparing-variables-for-analysis"><i class="fa fa-check"></i><b>10.1</b> Preparing variables for analysis</a></li>
<li class="chapter" data-level="10.2" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#correlation-and-simple-regression"><i class="fa fa-check"></i><b>10.2</b> Correlation and simple regression</a></li>
<li class="chapter" data-level="10.3" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#survey-weighted-regression-for-population-inference"><i class="fa fa-check"></i><b>10.3</b> Survey-weighted regression for population inference</a></li>
<li class="chapter" data-level="10.4" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#practice-exercises-2"><i class="fa fa-check"></i><b>10.4</b> Practice exercises</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html"><i class="fa fa-check"></i><b>11</b> Multiple Linear Regression</a>
<ul>
<li class="chapter" data-level="11.1" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#the-multiple-regression-model-and-its-interpretation"><i class="fa fa-check"></i><b>11.1</b> The multiple regression model and its interpretation</a></li>
<li class="chapter" data-level="11.2" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#data-and-analysis-sample"><i class="fa fa-check"></i><b>11.2</b> Data and analysis sample</a></li>
<li class="chapter" data-level="11.3" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#building-a-multiple-regression-model"><i class="fa fa-check"></i><b>11.3</b> Building a multiple regression model</a>
<ul>
<li class="chapter" data-level="11.3.1" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#comparing-coefficients-across-models"><i class="fa fa-check"></i><b>11.3.1</b> Comparing coefficients across models</a></li>
<li class="chapter" data-level="11.3.2" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#interpreting-categorical-predictors"><i class="fa fa-check"></i><b>11.3.2</b> Interpreting categorical predictors</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#extensions-interactions-and-non-linear-effects"><i class="fa fa-check"></i><b>11.4</b> Extensions: interactions and non-linear effects</a></li>
<li class="chapter" data-level="11.5" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#reporting-results"><i class="fa fa-check"></i><b>11.5</b> Reporting results</a></li>
<li class="chapter" data-level="11.6" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#practice-exercises-3"><i class="fa fa-check"></i><b>11.6</b> Practice exercises</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="logistic-regression.html"><a href="logistic-regression.html"><i class="fa fa-check"></i><b>12</b> Logistic Regression</a>
<ul>
<li class="chapter" data-level="12.1" data-path="logistic-regression.html"><a href="logistic-regression.html#what-logistic-regression-models"><i class="fa fa-check"></i><b>12.1</b> What logistic regression models</a></li>
<li class="chapter" data-level="12.2" data-path="logistic-regression.html"><a href="logistic-regression.html#simple-versus-multiple-logistic-regression"><i class="fa fa-check"></i><b>12.2</b> Simple versus multiple logistic regression</a></li>
<li class="chapter" data-level="12.3" data-path="logistic-regression.html"><a href="logistic-regression.html#data"><i class="fa fa-check"></i><b>12.3</b> Data</a>
<ul>
<li class="chapter" data-level="12.3.1" data-path="logistic-regression.html"><a href="logistic-regression.html#import-subset-and-keep-only-needed-variables"><i class="fa fa-check"></i><b>12.3.1</b> Import, subset, and keep only needed variables</a></li>
<li class="chapter" data-level="12.3.2" data-path="logistic-regression.html"><a href="logistic-regression.html#recode-variables-labels-reference-levels"><i class="fa fa-check"></i><b>12.3.2</b> Recode variables (labels + reference levels)</a></li>
<li class="chapter" data-level="12.3.3" data-path="logistic-regression.html"><a href="logistic-regression.html#why-we-need-survey-design-information"><i class="fa fa-check"></i><b>12.3.3</b> Why we need survey design information</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="logistic-regression.html"><a href="logistic-regression.html#simple-logistic-regression"><i class="fa fa-check"></i><b>12.4</b> Simple Logistic Regression</a>
<ul>
<li class="chapter" data-level="12.4.1" data-path="logistic-regression.html"><a href="logistic-regression.html#continuous-predictor-childs-age"><i class="fa fa-check"></i><b>12.4.1</b> Continuous predictor: child’s age</a></li>
<li class="chapter" data-level="12.4.2" data-path="logistic-regression.html"><a href="logistic-regression.html#categorical-predictor-example-books"><i class="fa fa-check"></i><b>12.4.2</b> Categorical predictor example: Books</a></li>
</ul></li>
<li class="chapter" data-level="12.5" data-path="logistic-regression.html"><a href="logistic-regression.html#multiple-binary-logistic-regression"><i class="fa fa-check"></i><b>12.5</b> Multiple binary logistic regression</a></li>
<li class="chapter" data-level="12.6" data-path="logistic-regression.html"><a href="logistic-regression.html#interaction"><i class="fa fa-check"></i><b>12.6</b> Interaction</a>
<ul>
<li class="chapter" data-level="12.6.1" data-path="logistic-regression.html"><a href="logistic-regression.html#interpretation-of-age-sex-and-the-agesex-interaction"><i class="fa fa-check"></i><b>12.6.1</b> Interpretation of age, sex, and the age*sex interaction</a></li>
</ul></li>
<li class="chapter" data-level="12.7" data-path="logistic-regression.html"><a href="logistic-regression.html#reporting-results-1"><i class="fa fa-check"></i><b>12.7</b> Reporting Results</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Analysis of Household Education Survey Data using R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="logistic-regression" class="section level1 hasAnchor" number="12">
<h1><span class="header-section-number">Chapter 12</span> Logistic Regression<a href="logistic-regression.html#logistic-regression" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Many questions in early-foundational learning research ask about the likelihood of a binary outcome - something that is either <em>“yes/no”</em> or <em>“0/1”</em>. For instance, how likely is a child to meet the minimum proficiency level in both maths and reading, given the child’s age and whether the language of assessment matches with the child’s home language. In this lesson, we use the ICAN-ICAR 2025 survey data to model binary outcomes using logistic regression.</p>
<p>A simple linear regression can be used as a “linear probability model”, but it often produces predicted values <em>below 0</em> or <em>above 1</em> and does not handle the changing variability that comes with binary outcomes. Logistic regression avoids these issues by modeling the log-odds of the outcome, which naturally maps to predicted probabilities between 0 and 1.</p>
<p>Because ICAN/ICAR is collected using a complex survey design (stratification, clustering, and survey weights), we fit models using the <em>survey</em> package: we first define the design with <code>svydesign()</code> and then estimate logistic regression with <code>svyglm()</code> so that standard errors and inference reflect the sampling design.</p>
<div id="what-logistic-regression-models" class="section level2 hasAnchor" number="12.1">
<h2><span class="header-section-number">12.1</span> What logistic regression models<a href="logistic-regression.html#what-logistic-regression-models" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Suppose <span class="math inline">\(Y\)</span> indicates whether a learner meets the MPL in maths, where <span class="math inline">\(Y = 1\)</span> means “meets MPL” and <span class="math inline">\(Y = 0\)</span> means “does not meet MPL”. Let <span class="math inline">\(X_1\)</span> be ICAN assessment time for maths.</p>
<div class="figure"><span style="display:block;" id="fig:fig-simplereg"></span>
<img src="figs/fig-simplereg-1.png" alt="Linear regression of a binary Y variable (0 = learner do not meet MPL for Maths, 1 = learner meets MPL for Maths) on a measurement X variable (child's age in years)." width="576" />
<p class="caption">
Figure 12.1: Linear regression of a binary Y variable (0 = learner do not meet MPL for Maths, 1 = learner meets MPL for Maths) on a measurement X variable (child’s age in years).
</p>
</div>
<p>A linear regression of a binary outcome is sometimes called a <em>linear probability model</em>. It can produce predicted values outside the <span class="math inline">\([0,1]\)</span> range. For example in <span class="citation">@fig-simplereg</span>, <span class="math display">\[\hat{Y} = -0.35 + 0.086X_1,\]</span>predictions exceed 1 when <span class="math inline">\(X_1 &gt; 15.8\)</span>. This is not meaningful because probabilities must lie between 0 and 1. In addition, with a binary outcome the variability changes with the mean (because <span class="math inline">\(Var(Y |X) = p(1- p)\)</span>), so the constant-variance assumption behind ordinary linear regression is not appropriate here.</p>
<p>Logistic regression starts by modeling the probability of “success”: <span class="math display">\[
p = P(Y = 1 | X).
\]</span> Since <span class="math inline">\(Y\)</span> is binary, <span class="math inline">\(P(Y = 0 | X) = 1-p\)</span>. The <strong>odds</strong> of meeting MPL are defined as <span class="math display">\[\text{odds} = \frac{p}{1 - p}.\]</span> Odds range from 0 to <span class="math inline">\(\infty\)</span>. For example, if <span class="math inline">\(p = 0.2\)</span>, then the odds are <span class="math inline">\(0.2/0.8 = 0.25\)</span>. You can say odds are 0.25 to 1,or 1 to 4.</p>
<p>Logistic regression assumes the <strong>log-odds</strong> (the logit) are linearly related with the predictors: <span class="math display">\[
\text{log}(\frac{p}{1-p}) = \beta_0 + \beta_1X_1
\]</span> Solving for <span class="math inline">\(p\)</span> gives the logistic curve: <span class="math display">\[
p = \frac{\text{exp}(\beta_0 + \beta_1X_1)}{1 + \text{exp}(\beta_0 + \beta_1X_1)},
\]</span> which always stays between 0 and 1. Here, <span class="math inline">\(\beta_1\)</span> is the change in the <strong>log-odds</strong> per one-unit increase in <span class="math inline">\(X_1\)</span>, and <span class="math inline">\(\text{exp}(\beta_1)\)</span> is the <strong>odds ratio</strong> associated with a one-unit increase in <span class="math inline">\(X_1\)</span>.</p>
<p>If the logit is a linearly related to the <span class="math inline">\(X\)</span> variables, then the probability <span class="math inline">\(p\)</span> is a non-linear, S-shaped function with respect to the <span class="math inline">\(X\)</span> variables as in <span class="citation">@fig-logreg</span>.</p>
<div class="figure"><span style="display:block;" id="fig:fig-logreg"></span>
<img src="figs/fig-logreg-1.png" alt="Predicted probability as a logit function X" width="576" />
<p class="caption">
Figure 12.2: Predicted probability as a logit function X
</p>
</div>
<p>Logistic regression is widely used in many fields whenever we want to predict the probability of a binary outcome (yes/no, 0/1). For example:</p>
<ul>
<li><p><strong>Medicine</strong>: to estimate the probability that a patient has (or will develop) a disease using medical history and test results.</p></li>
<li><p><strong>Banking/Finance</strong>: to estimate the probability that a borrower will default, based on income, credit history, and other profile information.</p></li>
<li><p><strong>Politics</strong>: to estimate the probability that a citizen will vote for a particular party or candidate.</p></li>
<li><p><strong>Many others</strong>: marketing (purchase vs not), education (pass vs fail), and program evaluation (participate vs not).</p></li>
</ul>
<p>In this lesson, we apply logistic regression to ICAN/ICAR survey data to model whether a learner meets the Minimum Proficiency Level (MPL).</p>
</div>
<div id="simple-versus-multiple-logistic-regression" class="section level2 hasAnchor" number="12.2">
<h2><span class="header-section-number">12.2</span> Simple versus multiple logistic regression<a href="logistic-regression.html#simple-versus-multiple-logistic-regression" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Binary logistic regression has an outcome <span class="math inline">\(Y\)</span> which has two categories (e.g., <span class="math inline">\(Y =1\)</span>, <span class="math inline">\(Y = 0\)</span>). We distinguish between two common forms:</p>
<ul>
<li><p>Simple logistic regression uses one predictor: <span class="math display">\[
\text{log}(\frac{p}{1-p}) = \beta_0+\beta_1X_1
\]</span></p></li>
<li><p>Multiple logistic regression uses two or more predictors: <span class="math display">\[
\text{log}(\frac{p}{1-p}) = \beta_0+\beta_1X_1+\beta_2X_2+\ldots+ \beta_kX_k
\]</span></p>
<p>Multiple logistic regression is often more useful because it lets us adjust for other factors. Each coefficient describes the relationship between a predictor and the outcome holding the other predictors constant.</p></li>
</ul>
<p>Because the ICAN/ICAR data come from a complex survey design, we estimate both simple and multiple logistic regression models using <code>svmglm()</code> with a design object created by <code>svydesign()</code>.</p>
</div>
<div id="data" class="section level2 hasAnchor" number="12.3">
<h2><span class="header-section-number">12.3</span> Data<a href="logistic-regression.html#data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We create an analysis-ready data by, (i) restricting to a specific country and learner subgroup, (ii) selecting a small set of variables needed for the models, and (iii) re-coding key variables into analysis-friendly formats (especially binary predictors and the MPL outcome).</p>
<ol style="list-style-type: decimal">
<li><p><code>ch02</code>: Child’s age</p></li>
<li><p><code>ch03</code>: Child’s sex</p></li>
<li><p><code>ch09</code>: Has the child brought any material to read (other than school textbooks) from the school library</p></li>
<li><p><code>MPLBoth</code>: Whether the learner meets minimum proficiency level in both maths and reading</p></li>
<li><p><code>CountryName</code>: Unique country name</p></li>
<li><p><code>TierOneUnit</code>: Geographical divisions within one country (county, state, province, etc)</p></li>
<li><p><code>VillageID</code>: Unique village identifiers</p></li>
<li><p><code>HHID</code>: Unique household identifier</p></li>
</ol>
<div id="import-subset-and-keep-only-needed-variables" class="section level3 hasAnchor" number="12.3.1">
<h3><span class="header-section-number">12.3.1</span> Import, subset, and keep only needed variables<a href="logistic-regression.html#import-subset-and-keep-only-needed-variables" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb427"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb427-1"><a href="logistic-regression.html#cb427-1" tabindex="-1"></a><span class="co"># load packages</span></span>
<span id="cb427-2"><a href="logistic-regression.html#cb427-2" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb427-3"><a href="logistic-regression.html#cb427-3" tabindex="-1"></a><span class="fu">library</span>(survey)</span>
<span id="cb427-4"><a href="logistic-regression.html#cb427-4" tabindex="-1"></a><span class="fu">library</span>(skimr)</span>
<span id="cb427-5"><a href="logistic-regression.html#cb427-5" tabindex="-1"></a></span>
<span id="cb427-6"><a href="logistic-regression.html#cb427-6" tabindex="-1"></a><span class="co"># load the data</span></span>
<span id="cb427-7"><a href="logistic-regression.html#cb427-7" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;data/ican-icar-2025-v1.csv&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb427-8"><a href="logistic-regression.html#cb427-8" tabindex="-1"></a>  <span class="fu">filter</span>(</span>
<span id="cb427-9"><a href="logistic-regression.html#cb427-9" tabindex="-1"></a>    CountryName <span class="sc">==</span> <span class="st">&quot;Senegal&quot;</span> <span class="sc">&amp;</span> <span class="co"># restrict to this country</span></span>
<span id="cb427-10"><a href="logistic-regression.html#cb427-10" tabindex="-1"></a>      EnrolmentStatus <span class="sc">==</span> <span class="st">&quot;Currently Enrolled&quot;</span> <span class="co"># currently enrolled in school</span></span>
<span id="cb427-11"><a href="logistic-regression.html#cb427-11" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb427-12"><a href="logistic-regression.html#cb427-12" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb427-13"><a href="logistic-regression.html#cb427-13" tabindex="-1"></a>    Location, CountryName, TierOneUnit, VillageID, HHID,</span>
<span id="cb427-14"><a href="logistic-regression.html#cb427-14" tabindex="-1"></a>    HHWeightProvided, ch02, ch03, ch09, MPLBoth</span>
<span id="cb427-15"><a href="logistic-regression.html#cb427-15" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb427-16"><a href="logistic-regression.html#cb427-16" tabindex="-1"></a>  <span class="fu">rename</span>(</span>
<span id="cb427-17"><a href="logistic-regression.html#cb427-17" tabindex="-1"></a>    <span class="at">age =</span> ch02,</span>
<span id="cb427-18"><a href="logistic-regression.html#cb427-18" tabindex="-1"></a>    <span class="at">sex =</span> ch03,</span>
<span id="cb427-19"><a href="logistic-regression.html#cb427-19" tabindex="-1"></a>    <span class="at">books =</span> ch09,</span>
<span id="cb427-20"><a href="logistic-regression.html#cb427-20" tabindex="-1"></a>    <span class="at">mpl_both =</span> MPLBoth</span>
<span id="cb427-21"><a href="logistic-regression.html#cb427-21" tabindex="-1"></a>  )</span></code></pre></div>
</div>
<div id="recode-variables-labels-reference-levels" class="section level3 hasAnchor" number="12.3.2">
<h3><span class="header-section-number">12.3.2</span> Recode variables (labels + reference levels)<a href="logistic-regression.html#recode-variables-labels-reference-levels" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb428"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb428-1"><a href="logistic-regression.html#cb428-1" tabindex="-1"></a>dat <span class="ot">&lt;-</span> dat <span class="sc">|&gt;</span></span>
<span id="cb428-2"><a href="logistic-regression.html#cb428-2" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb428-3"><a href="logistic-regression.html#cb428-3" tabindex="-1"></a>    <span class="co"># Outcome (0/1 -&gt; No/Yes)</span></span>
<span id="cb428-4"><a href="logistic-regression.html#cb428-4" tabindex="-1"></a>    <span class="at">mpl_both =</span> <span class="fu">factor</span>(mpl_both, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;No&quot;</span>, <span class="st">&quot;Yes&quot;</span>)),</span>
<span id="cb428-5"><a href="logistic-regression.html#cb428-5" tabindex="-1"></a></span>
<span id="cb428-6"><a href="logistic-regression.html#cb428-6" tabindex="-1"></a>    <span class="co"># Binary predictors (0/1 -&gt; No/Yes)</span></span>
<span id="cb428-7"><a href="logistic-regression.html#cb428-7" tabindex="-1"></a>    <span class="at">books =</span> <span class="fu">factor</span>(books, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;No&quot;</span>, <span class="st">&quot;Yes&quot;</span>)),</span>
<span id="cb428-8"><a href="logistic-regression.html#cb428-8" tabindex="-1"></a>    <span class="at">sex =</span> <span class="fu">factor</span>(sex, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Female&quot;</span>, <span class="st">&quot;Male&quot;</span>)),</span>
<span id="cb428-9"><a href="logistic-regression.html#cb428-9" tabindex="-1"></a>    <span class="at">Location =</span> <span class="fu">factor</span>(Location)</span>
<span id="cb428-10"><a href="logistic-regression.html#cb428-10" tabindex="-1"></a>  )</span></code></pre></div>
<p>Always recognize the order of the levels for the dependent variable because it will have an impact on the interpretations. In R, the first level from <code>levels()</code> is always taken as the reference level.</p>
<p>In our case, the first level is not meeting the MPL and the second level is meeting the MPL for both maths and reading.</p>
<div class="sourceCode" id="cb429"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb429-1"><a href="logistic-regression.html#cb429-1" tabindex="-1"></a><span class="fu">levels</span>(dat<span class="sc">$</span>mpl_both)</span></code></pre></div>
<pre><code>## [1] &quot;No&quot;  &quot;Yes&quot;</code></pre>
<p>This means that when we estimate the impact of the independent variable(s) it will be on the learner meeting the MPL (and not on the learner not meeting the MPL).</p>
<p>Here is the preview of the data and some descriptive statistics.</p>
<div class="sourceCode" id="cb431"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb431-1"><a href="logistic-regression.html#cb431-1" tabindex="-1"></a>dat <span class="sc">|&gt;</span></span>
<span id="cb431-2"><a href="logistic-regression.html#cb431-2" tabindex="-1"></a>  <span class="fu">skim</span>()</span></code></pre></div>
<table>
<caption><span id="tab:unnamed-chunk-207">Table 12.1: </span>Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">dat</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">7100</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">10</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">character</td>
<td align="left">4</td>
</tr>
<tr class="odd">
<td align="left">factor</td>
<td align="left">4</td>
</tr>
<tr class="even">
<td align="left">numeric</td>
<td align="left">2</td>
</tr>
<tr class="odd">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table>
<colgroup>
<col width="19%" />
<col width="13%" />
<col width="19%" />
<col width="5%" />
<col width="5%" />
<col width="8%" />
<col width="12%" />
<col width="15%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">min</th>
<th align="right">max</th>
<th align="right">empty</th>
<th align="right">n_unique</th>
<th align="right">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">CountryName</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">7</td>
<td align="right">7</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">TierOneUnit</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">4</td>
<td align="right">4</td>
<td align="right">0</td>
<td align="right">14</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">VillageID</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">4</td>
<td align="right">4</td>
<td align="right">0</td>
<td align="right">201</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">HHID</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">41</td>
<td align="right">41</td>
<td align="right">0</td>
<td align="right">3489</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: factor</strong></p>
<table>
<colgroup>
<col width="18%" />
<col width="13%" />
<col width="18%" />
<col width="10%" />
<col width="11%" />
<col width="27%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="left">ordered</th>
<th align="right">n_unique</th>
<th align="left">top_counts</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Location</td>
<td align="right">0</td>
<td align="right">1.000</td>
<td align="left">FALSE</td>
<td align="right">2</td>
<td align="left">Urb: 4308, Rur: 2792</td>
</tr>
<tr class="even">
<td align="left">sex</td>
<td align="right">0</td>
<td align="right">1.000</td>
<td align="left">FALSE</td>
<td align="right">2</td>
<td align="left">Fem: 4119, Mal: 2981</td>
</tr>
<tr class="odd">
<td align="left">books</td>
<td align="right">0</td>
<td align="right">1.000</td>
<td align="left">FALSE</td>
<td align="right">2</td>
<td align="left">No: 5812, Yes: 1288</td>
</tr>
<tr class="even">
<td align="left">mpl_both</td>
<td align="right">671</td>
<td align="right">0.905</td>
<td align="left">FALSE</td>
<td align="right">2</td>
<td align="left">No: 4755, Yes: 1674</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<colgroup>
<col width="20%" />
<col width="12%" />
<col width="17%" />
<col width="7%" />
<col width="8%" />
<col width="4%" />
<col width="4%" />
<col width="4%" />
<col width="4%" />
<col width="6%" />
<col width="7%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">HHWeightProvided</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">538.4</td>
<td align="right">179.22</td>
<td align="right">188</td>
<td align="right">448</td>
<td align="right">531</td>
<td align="right">603</td>
<td align="right">1332</td>
<td align="left">▃▇▂▁▁</td>
</tr>
<tr class="even">
<td align="left">age</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">10.6</td>
<td align="right">3.11</td>
<td align="right">5</td>
<td align="right">8</td>
<td align="right">11</td>
<td align="right">13</td>
<td align="right">16</td>
<td align="left">▇▇▇▇▇</td>
</tr>
</tbody>
</table>
</div>
<div id="why-we-need-survey-design-information" class="section level3 hasAnchor" number="12.3.3">
<h3><span class="header-section-number">12.3.3</span> Why we need survey design information<a href="logistic-regression.html#why-we-need-survey-design-information" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The ICAN/ICAR data come from a complex, multi-stage sample (clustered and stratified). To get correct standard errors, we create a survey design object that tells R which variables represent strata, primary sampling units (PSUs), and sampling weights. After this step, we fit models using <code>svyglm()</code> with the design object rather than using <code>glm()</code> directly.</p>
<div class="sourceCode" id="cb432"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb432-1"><a href="logistic-regression.html#cb432-1" tabindex="-1"></a><span class="fu">options</span>(</span>
<span id="cb432-2"><a href="logistic-regression.html#cb432-2" tabindex="-1"></a>  <span class="at">survey.lonely.psu =</span> <span class="st">&quot;adjust&quot;</span>,</span>
<span id="cb432-3"><a href="logistic-regression.html#cb432-3" tabindex="-1"></a>  <span class="at">survey.adjust.domain.lonely =</span> <span class="cn">TRUE</span></span>
<span id="cb432-4"><a href="logistic-regression.html#cb432-4" tabindex="-1"></a>)</span>
<span id="cb432-5"><a href="logistic-regression.html#cb432-5" tabindex="-1"></a></span>
<span id="cb432-6"><a href="logistic-regression.html#cb432-6" tabindex="-1"></a></span>
<span id="cb432-7"><a href="logistic-regression.html#cb432-7" tabindex="-1"></a>des <span class="ot">&lt;-</span> <span class="fu">svydesign</span>(</span>
<span id="cb432-8"><a href="logistic-regression.html#cb432-8" tabindex="-1"></a>  <span class="at">ids =</span> <span class="sc">~</span> <span class="fu">interaction</span>(CountryName, VillageID) <span class="sc">+</span> HHID,</span>
<span id="cb432-9"><a href="logistic-regression.html#cb432-9" tabindex="-1"></a>  <span class="at">strata =</span> <span class="sc">~</span> <span class="fu">interaction</span>(CountryName, TierOneUnit),</span>
<span id="cb432-10"><a href="logistic-regression.html#cb432-10" tabindex="-1"></a>  <span class="at">weights =</span> <span class="sc">~</span>HHWeightProvided,</span>
<span id="cb432-11"><a href="logistic-regression.html#cb432-11" tabindex="-1"></a>  <span class="at">nest =</span> <span class="cn">TRUE</span>,</span>
<span id="cb432-12"><a href="logistic-regression.html#cb432-12" tabindex="-1"></a>  <span class="at">data =</span> dat</span>
<span id="cb432-13"><a href="logistic-regression.html#cb432-13" tabindex="-1"></a>)</span></code></pre></div>
</div>
</div>
<div id="simple-logistic-regression" class="section level2 hasAnchor" number="12.4">
<h2><span class="header-section-number">12.4</span> Simple Logistic Regression<a href="logistic-regression.html#simple-logistic-regression" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A simple logistic regression models a binary outcome using one predictor.</p>
<p>We will illustrate simple logistic regression with:</p>
<ol style="list-style-type: decimal">
<li>a continuous predictor, and</li>
<li>a categorical predictor.</li>
</ol>
<div id="continuous-predictor-childs-age" class="section level3 hasAnchor" number="12.4.1">
<h3><span class="header-section-number">12.4.1</span> Continuous predictor: child’s age<a href="logistic-regression.html#continuous-predictor-childs-age" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Suppose we want to model whether a learner meets MPL for both maths and reading (<code>MPL_both</code>) using the the child’s age (<code>age</code>). Here.</p>
<div class="sourceCode" id="cb433"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb433-1"><a href="logistic-regression.html#cb433-1" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">svyglm</span>(mpl_both <span class="sc">~</span> age,</span>
<span id="cb433-2"><a href="logistic-regression.html#cb433-2" tabindex="-1"></a>  <span class="at">family =</span> quasibinomial,</span>
<span id="cb433-3"><a href="logistic-regression.html#cb433-3" tabindex="-1"></a>  <span class="at">design =</span> des,</span>
<span id="cb433-4"><a href="logistic-regression.html#cb433-4" tabindex="-1"></a>  <span class="at">na.action =</span> na.omit</span>
<span id="cb433-5"><a href="logistic-regression.html#cb433-5" tabindex="-1"></a>)</span>
<span id="cb433-6"><a href="logistic-regression.html#cb433-6" tabindex="-1"></a>m1 <span class="sc">|&gt;</span></span>
<span id="cb433-7"><a href="logistic-regression.html#cb433-7" tabindex="-1"></a>  <span class="fu">tidy</span>()</span></code></pre></div>
<pre><code>## # A tibble: 2 × 5
##   term        estimate std.error statistic  p.value
##   &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1 (Intercept)   -5.49     0.181      -30.3 8.04e-74
## 2 age            0.391    0.0144      27.2 1.21e-66</code></pre>
<div id="interpreting-the-coefficient-log-odds" class="section level4 hasAnchor" number="12.4.1.1">
<h4><span class="header-section-number">12.4.1.1</span> Interpreting the coefficient (log-odds)<a href="logistic-regression.html#interpreting-the-coefficient-log-odds" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>In a logistic model,</p>
<p><span class="math display">\[
\text{log}(\frac{p}{1-p}) = \beta_0+\beta_1X
\]</span></p>
<p>so <span class="math inline">\(\beta_1\)</span> is the change in log-odds for a one-unit increase in <span class="math inline">\(X\)</span> (here, one more year in child’s age). If <span class="math inline">\(\beta_1 &gt; 0\)</span>: odds (and probability) of meeting MPL for both tends to increase as <span class="math inline">\(X\)</span> increases. If <span class="math inline">\(\beta_1 &lt; 0\)</span>: odds (and probability) of meeting MPL for both tend to decrease as <span class="math inline">\(X\)</span> increases.</p>
<p>Here, <span class="math inline">\(\hat{\beta_1} \approx 0.39\)</span>, meaning that one year increase in child’s age leads to <span class="math inline">\(0.39\)</span> increase in the log odds of a child meeting MPL for both maths and reading. Older children are <em>more likely</em> in odds terms to meet MPL for both maths and reading, holding the model as specified.</p>
</div>
<div id="interpreting-the-odds-ratio" class="section level4 hasAnchor" number="12.4.1.2">
<h4><span class="header-section-number">12.4.1.2</span> Interpreting the odds ratio<a href="logistic-regression.html#interpreting-the-odds-ratio" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Exponentiation of the <span class="math inline">\(\hat{\beta_1}\)</span> coefficient converts back to the odds ratio of a child meeting MPL for both <span class="math inline">\((Y = 1)\)</span>.</p>
<div class="sourceCode" id="cb435"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb435-1"><a href="logistic-regression.html#cb435-1" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(m1)[<span class="st">&quot;age&quot;</span>])</span></code></pre></div>
<pre><code>##  age 
## 1.48</code></pre>
<p>We can say that an additional year in the child’s age multiplies odds of meeting MPL by <span class="math inline">\(~1.48\)</span>. This means that the odds of meeting MPL for both maths and reading are about <span class="math inline">\(48\%\)</span> higher per additional year in the child’s age (because <span class="math inline">\(1.4785 - 1 \approx 0.4785\)</span>).</p>
<p>Also, R performs a hypothesis test for each coefficient, that is <span class="math inline">\(H_0: \beta_j = 0\)</span> versus <span class="math inline">\(H_0: \beta_j \neq 0\)</span> for <span class="math inline">\(j = [0, 1]\)</span> via the Wald test, and prints the <em>p</em>-values in the last column. We can thus compare these <em>p-</em>values to the chosen significance level (usually <span class="math inline">\(\alpha = 0.05\)</span>) to conclude whether or not each of the coefficient is significantly different from zero. The lower the <em>p</em>-value, the more evidence that the coefficient is different from zero. This is similar to the linear regression.</p>
<p>Here, the <em>p</em>-value <span class="math inline">\(&lt; 0.05\)</span>. This means that there is sufficient evidence that the age coefficient is statistically different from zero at the <span class="math inline">\(5\%\)</span> significance level.</p>
</div>
<div id="predicted-probabilities" class="section level4 hasAnchor" number="12.4.1.3">
<h4><span class="header-section-number">12.4.1.3</span> Predicted probabilities<a href="logistic-regression.html#predicted-probabilities" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>A good next step is to use the model to compute the predicted probabilities for few ages. Suppose we would like to predict the probability of meeting MPL for both maths and reading for a child that is aged <span class="math inline">\(7, 10, 13, 16\)</span>:</p>
<div class="sourceCode" id="cb437"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb437-1"><a href="logistic-regression.html#cb437-1" tabindex="-1"></a>newdat <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">age =</span> <span class="fu">c</span>(<span class="dv">7</span>, <span class="dv">10</span>, <span class="dv">13</span>, <span class="dv">16</span>))</span>
<span id="cb437-2"><a href="logistic-regression.html#cb437-2" tabindex="-1"></a></span>
<span id="cb437-3"><a href="logistic-regression.html#cb437-3" tabindex="-1"></a><span class="co"># get predictions on the link (logit) scale</span></span>
<span id="cb437-4"><a href="logistic-regression.html#cb437-4" tabindex="-1"></a>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(m1, <span class="at">newdata =</span> newdat)</span>
<span id="cb437-5"><a href="logistic-regression.html#cb437-5" tabindex="-1"></a>newdat<span class="sc">$</span>probabilities <span class="ot">&lt;-</span> <span class="fu">plogis</span>(pred) <span class="co"># convert logit --&gt; probability</span></span>
<span id="cb437-6"><a href="logistic-regression.html#cb437-6" tabindex="-1"></a></span>
<span id="cb437-7"><a href="logistic-regression.html#cb437-7" tabindex="-1"></a>newdat</span></code></pre></div>
<pre><code>##   age probabilities
## 1   7        0.0596
## 2  10        0.1701
## 3  13        0.3983
## 4  16        0.6814</code></pre>
<p>As the child grows in years the likelihood of them meeting the MPL for both increases substantially. We can also visualize the results of our model below:</p>
<div class="sourceCode" id="cb439"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb439-1"><a href="logistic-regression.html#cb439-1" tabindex="-1"></a><span class="fu">library</span>(sjPlot)</span>
<span id="cb439-2"><a href="logistic-regression.html#cb439-2" tabindex="-1"></a></span>
<span id="cb439-3"><a href="logistic-regression.html#cb439-3" tabindex="-1"></a><span class="co"># plot</span></span>
<span id="cb439-4"><a href="logistic-regression.html#cb439-4" tabindex="-1"></a><span class="fu">plot_model</span>(</span>
<span id="cb439-5"><a href="logistic-regression.html#cb439-5" tabindex="-1"></a>  m1,</span>
<span id="cb439-6"><a href="logistic-regression.html#cb439-6" tabindex="-1"></a>  <span class="at">type =</span> <span class="st">&quot;pred&quot;</span>,</span>
<span id="cb439-7"><a href="logistic-regression.html#cb439-7" tabindex="-1"></a>  <span class="at">terms =</span> <span class="st">&quot;age&quot;</span></span>
<span id="cb439-8"><a href="logistic-regression.html#cb439-8" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb439-9"><a href="logistic-regression.html#cb439-9" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb439-10"><a href="logistic-regression.html#cb439-10" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Probability of MPL for both maths &amp; reading&quot;</span>,</span>
<span id="cb439-11"><a href="logistic-regression.html#cb439-11" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Child&#39;s Age in Years&quot;</span>,</span>
<span id="cb439-12"><a href="logistic-regression.html#cb439-12" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Predicted Probabilities of MPL for both Maths &amp; Reading using Age&quot;</span></span>
<span id="cb439-13"><a href="logistic-regression.html#cb439-13" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb439-14"><a href="logistic-regression.html#cb439-14" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code></pre></div>
<p><img src="figs/model%20plot-1.png" width="672" /></p>
<p>The above plot shows that probability of a child meeting MPL for both reading and maths increases with the child’s age.</p>
</div>
</div>
<div id="categorical-predictor-example-books" class="section level3 hasAnchor" number="12.4.2">
<h3><span class="header-section-number">12.4.2</span> Categorical predictor example: Books<a href="logistic-regression.html#categorical-predictor-example-books" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Suppose we are now interested in predicting the probability of a child meeting MPL for both using whether the child has brought home any material (other than textbooks) to read from the school library (<code>books</code>).</p>
<p>Recall that when the predictor was continuous, <span class="math inline">\(e^{\hat{\beta_1}}\)</span> was the multiplicative change in the odds in favor of <span class="math inline">\(Y = 1\)</span> as <span class="math inline">\(X_1\)</span> increases by one unit. With <span class="math inline">\(X_1\)</span> being <code>books</code>, a categorical variable, the only increase possible is 0 to 1 (or from 1 to 2 if <code>sex</code> is encoded as a factor). So, we can write the interpretation in terms of <em>Yes/No</em>: <span class="math inline">\(e^{\hat{\beta_1}}\)</span> is the multiplicative change of the odds in favor of <span class="math inline">\(Y = 1\)</span> as <em>No</em> becomes <em>Yes</em>, keeping in mind the order of the level for the variable <code>books</code>.</p>
<div class="sourceCode" id="cb440"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb440-1"><a href="logistic-regression.html#cb440-1" tabindex="-1"></a><span class="co"># levels for books variable</span></span>
<span id="cb440-2"><a href="logistic-regression.html#cb440-2" tabindex="-1"></a><span class="fu">levels</span>(dat<span class="sc">$</span>books)</span></code></pre></div>
<pre><code>## [1] &quot;No&quot;  &quot;Yes&quot;</code></pre>
<p>So, it is indeed the multiplicative change of the odds in favor of <span class="math inline">\(Y = 1\)</span> as <strong>No becomes Yes.</strong> If the level <em>No</em> came before the level <em>Yes</em> in the data, it would have been the opposite. We fit the model again:</p>
<div class="sourceCode" id="cb442"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb442-1"><a href="logistic-regression.html#cb442-1" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">svyglm</span>(mpl_both <span class="sc">~</span> books,</span>
<span id="cb442-2"><a href="logistic-regression.html#cb442-2" tabindex="-1"></a>  <span class="at">family =</span> quasibinomial,</span>
<span id="cb442-3"><a href="logistic-regression.html#cb442-3" tabindex="-1"></a>  <span class="at">design =</span> des,</span>
<span id="cb442-4"><a href="logistic-regression.html#cb442-4" tabindex="-1"></a>  <span class="at">na.action =</span> na.omit</span>
<span id="cb442-5"><a href="logistic-regression.html#cb442-5" tabindex="-1"></a>)</span>
<span id="cb442-6"><a href="logistic-regression.html#cb442-6" tabindex="-1"></a></span>
<span id="cb442-7"><a href="logistic-regression.html#cb442-7" tabindex="-1"></a>m2 <span class="sc">|&gt;</span></span>
<span id="cb442-8"><a href="logistic-regression.html#cb442-8" tabindex="-1"></a>  <span class="fu">tidy</span>()</span></code></pre></div>
<pre><code>## # A tibble: 2 × 5
##   term        estimate std.error statistic  p.value
##   &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1 (Intercept)   -1.14     0.0634    -17.9  2.08e-42
## 2 booksYes       0.487    0.0937      5.19 5.45e- 7</code></pre>
<div id="interpreting-the-coefficient-log-odds-1" class="section level4 hasAnchor" number="12.4.2.1">
<h4><span class="header-section-number">12.4.2.1</span> Interpreting the coefficient (log-odds)<a href="logistic-regression.html#interpreting-the-coefficient-log-odds-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>As the <em>No</em> becomes <em>Yes</em>, the log-odds of meeting MPL for both changes by <span class="math inline">\(0.492\)</span>. The odds (and probabilities) tend to <em>increase</em> as the child start to bring back materials to read from the school library.</p>
</div>
<div id="interpreting-the-odds-ratio-1" class="section level4 hasAnchor" number="12.4.2.2">
<h4><span class="header-section-number">12.4.2.2</span> Interpreting the odds ratio<a href="logistic-regression.html#interpreting-the-odds-ratio-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Odds ratio for <code>books</code> variable are</p>
<div class="sourceCode" id="cb444"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb444-1"><a href="logistic-regression.html#cb444-1" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(m2)[<span class="st">&quot;booksYes&quot;</span>])</span></code></pre></div>
<pre><code>## booksYes 
##     1.63</code></pre>
<p>For children that bring home study materials from the school library, their odds of meeting MPL is multiplied by a factor of <span class="math inline">\(e^{0.492} = 1.635\)</span> relative to those who do not bring back home study materials from the school library. This means that the odds of meeting MPL for both reading and maths are <span class="math inline">\((1.635 -1)*100 = 63.5\%\)</span> higher for those children who bring home study materials from the school library than those who do not bring back home study materials.</p>
<p>The interpretation of the intercept <span class="math inline">\(\hat{\beta_0} = -1.138\)</span> gives the probability of a child meeting MPL when <span class="math inline">\(X= 0\)</span>. In our case, this simply maps to those children who do not bring back study materials from the school library. Therefore, the probability of a a child who does not bring back home study material meeting MPL for both reading and math is:</p>
<div class="sourceCode" id="cb446"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb446-1"><a href="logistic-regression.html#cb446-1" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(m2)[<span class="dv">1</span>]) <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> <span class="fu">exp</span>(<span class="fu">coef</span>(m2)[<span class="dv">1</span>]))</span></code></pre></div>
<pre><code>## (Intercept) 
##       0.243</code></pre>
<p>The model’s intercept tells us that the probability of a child that does not bring back home study materials from the school library meeting MPL for both is only <span class="math inline">\(24,2\%\)</span>.</p>
</div>
<div id="predicted-probabilities-1" class="section level4 hasAnchor" number="12.4.2.3">
<h4><span class="header-section-number">12.4.2.3</span> Predicted probabilities<a href="logistic-regression.html#predicted-probabilities-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>As with the continuous predictor, predictions can also be made with the <code>predict()</code> function. Suppose we want to predict the probability of a child who brings back home study material from the school library meeting MPL for both reading and math:</p>
<div class="sourceCode" id="cb448"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb448-1"><a href="logistic-regression.html#cb448-1" tabindex="-1"></a><span class="co"># predict probability to meet MPL</span></span>
<span id="cb448-2"><a href="logistic-regression.html#cb448-2" tabindex="-1"></a>newdat <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">books =</span> <span class="fu">c</span>(<span class="st">&quot;Yes&quot;</span>, <span class="st">&quot;No&quot;</span>))</span>
<span id="cb448-3"><a href="logistic-regression.html#cb448-3" tabindex="-1"></a>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(m2,</span>
<span id="cb448-4"><a href="logistic-regression.html#cb448-4" tabindex="-1"></a>  <span class="at">newdata =</span> newdat,</span>
<span id="cb448-5"><a href="logistic-regression.html#cb448-5" tabindex="-1"></a>  <span class="at">type    =</span> <span class="st">&quot;link&quot;</span></span>
<span id="cb448-6"><a href="logistic-regression.html#cb448-6" tabindex="-1"></a>)</span>
<span id="cb448-7"><a href="logistic-regression.html#cb448-7" tabindex="-1"></a></span>
<span id="cb448-8"><a href="logistic-regression.html#cb448-8" tabindex="-1"></a>newdat<span class="sc">$</span>probabilities <span class="ot">&lt;-</span> <span class="fu">plogis</span>(pred)</span>
<span id="cb448-9"><a href="logistic-regression.html#cb448-9" tabindex="-1"></a></span>
<span id="cb448-10"><a href="logistic-regression.html#cb448-10" tabindex="-1"></a>newdat</span></code></pre></div>
<pre><code>##   books probabilities
## 1   Yes         0.343
## 2    No         0.243</code></pre>
<p>Based on this model, it is predicted that a child who brings back home study material from the school library has a <span class="math inline">\(34,4\%\)</span> chance of meeting MPL for both reading and math. This is higher relative to those children who do not bring back home study materials.</p>
<p>We can also visualize these results using the <code>plot_model</code> function:</p>
<div class="sourceCode" id="cb450"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb450-1"><a href="logistic-regression.html#cb450-1" tabindex="-1"></a><span class="co"># plot</span></span>
<span id="cb450-2"><a href="logistic-regression.html#cb450-2" tabindex="-1"></a></span>
<span id="cb450-3"><a href="logistic-regression.html#cb450-3" tabindex="-1"></a><span class="fu">plot_model</span>(m2,</span>
<span id="cb450-4"><a href="logistic-regression.html#cb450-4" tabindex="-1"></a>  <span class="at">type =</span> <span class="st">&quot;pred&quot;</span>,</span>
<span id="cb450-5"><a href="logistic-regression.html#cb450-5" tabindex="-1"></a>  <span class="at">terms =</span> <span class="st">&quot;books&quot;</span></span>
<span id="cb450-6"><a href="logistic-regression.html#cb450-6" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb450-7"><a href="logistic-regression.html#cb450-7" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb450-8"><a href="logistic-regression.html#cb450-8" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Probability of MPL for both maths &amp; reading&quot;</span>,</span>
<span id="cb450-9"><a href="logistic-regression.html#cb450-9" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Predicted Probabilities of MPL for both Maths &amp; Reading using Books&quot;</span></span>
<span id="cb450-10"><a href="logistic-regression.html#cb450-10" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb450-11"><a href="logistic-regression.html#cb450-11" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code></pre></div>
<p><img src="figs/unnamed-chunk-212-1.png" width="672" /></p>
<p>The points correspond to the predicted probabilities, and the bars correspond to their confidence intervals.</p>
</div>
</div>
</div>
<div id="multiple-binary-logistic-regression" class="section level2 hasAnchor" number="12.5">
<h2><span class="header-section-number">12.5</span> Multiple binary logistic regression<a href="logistic-regression.html#multiple-binary-logistic-regression" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The interpretation of the coefficients in multiple logistic regression is similar to that of simple logistic regression, except that this time it estimates the multiplicative change in the log-odds in favor of <span class="math inline">\(Y = 1\)</span> when <span class="math inline">\(X\)</span> increases by one unit, while holding other predictors constant.</p>
<p>For this illustration, suppose we want to predict the MPL for both reading and math using <code>age</code>. <code>sex</code>, and <code>books</code>.</p>
<div class="sourceCode" id="cb451"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb451-1"><a href="logistic-regression.html#cb451-1" tabindex="-1"></a><span class="co"># fit the model</span></span>
<span id="cb451-2"><a href="logistic-regression.html#cb451-2" tabindex="-1"></a>m3 <span class="ot">&lt;-</span> <span class="fu">svyglm</span>(mpl_both <span class="sc">~</span> age <span class="sc">+</span> sex <span class="sc">+</span> books,</span>
<span id="cb451-3"><a href="logistic-regression.html#cb451-3" tabindex="-1"></a>  <span class="at">family =</span> quasibinomial,</span>
<span id="cb451-4"><a href="logistic-regression.html#cb451-4" tabindex="-1"></a>  <span class="at">design =</span> des,</span>
<span id="cb451-5"><a href="logistic-regression.html#cb451-5" tabindex="-1"></a>  <span class="at">na.action =</span> na.omit</span>
<span id="cb451-6"><a href="logistic-regression.html#cb451-6" tabindex="-1"></a>)</span>
<span id="cb451-7"><a href="logistic-regression.html#cb451-7" tabindex="-1"></a><span class="co"># print results</span></span>
<span id="cb451-8"><a href="logistic-regression.html#cb451-8" tabindex="-1"></a>m3 <span class="sc">|&gt;</span></span>
<span id="cb451-9"><a href="logistic-regression.html#cb451-9" tabindex="-1"></a>  <span class="fu">tidy</span>()</span></code></pre></div>
<pre><code>## # A tibble: 4 × 5
##   term        estimate std.error statistic  p.value
##   &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1 (Intercept)  -5.53      0.178    -31.0   5.90e-75
## 2 age           0.389     0.0143    27.2   2.80e-66
## 3 sexMale      -0.0488    0.0707    -0.690 4.91e- 1
## 4 booksYes      0.387     0.105      3.71  2.79e- 4</code></pre>
<p>Based on the <em>p</em>-values, we can conclude that, at the <span class="math inline">\(5\%\)</span> significance level, only <code>age</code> and <code>books</code> are significantly associated with MPL for both reading and math (<em>p-</em>value <span class="math inline">\(&lt; 0.05\)</span>).</p>
<p>Similar to simple logistic regression, it is easier to interpret these relationships through the odds ratios. But this time, we also print <span class="math inline">\(95\%\)</span> CI of the odds ratios in addition to the OR (rounded to 3 decimals) so that we can easily see which ones are significantly different from 1. If <span class="math inline">\(95\%\)</span> CI include the value of 1 in their bound, then there is no significant association between the MPL both and the predictor in question. This is another way of confirming the significance of a predictor.</p>
<div class="sourceCode" id="cb453"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb453-1"><a href="logistic-regression.html#cb453-1" tabindex="-1"></a><span class="co"># OR and 95% CI</span></span>
<span id="cb453-2"><a href="logistic-regression.html#cb453-2" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">exp</span>(<span class="fu">cbind</span>(<span class="at">OR =</span> <span class="fu">coef</span>(m3), <span class="fu">confint</span>(m3))), <span class="dv">3</span>)</span></code></pre></div>
<pre><code>##                OR 2.5 % 97.5 %
## (Intercept) 0.004 0.003  0.006
## age         1.476 1.435  1.518
## sexMale     0.952 0.828  1.095
## booksYes    1.473 1.199  1.810</code></pre>
<p>From the OR and their <span class="math inline">\(95\%\)</span> CI computed above, we can conclude that:</p>
<ul>
<li><p><code>age</code>: an additional year in the child’s age multiplies odds of meeting MPL by <span class="math inline">\(~1.48\)</span>.This means that the odds of meeting MPL for both maths and reading are about <span class="math inline">\(48\%\)</span> higher per additional year in the child’s age, <em>ceteris paribus</em>.</p></li>
<li><p><code>books</code>: the odds of a child that brings back home study material from the school library meeting MPL for both reading and math are <span class="math inline">\(1.473\)</span> times higher than the child who does not bring back home study material, <em>ceteris paribus</em>.</p></li>
</ul>
<p>We refrain from interpreting the <code>sex</code> as it not significant at the <span class="math inline">\(5\%\)</span> significance level (also, 1 is included in its <span class="math inline">\(95\%\)</span> CI).</p>
<p>For illustrative purposes, suppose now we want to predict the probability that a new child meets MPL for both reading and math. Suppose that this child is from Senegal, aged 15 years old, male, and does not bring back home study material from the school library:</p>
<div class="sourceCode" id="cb455"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb455-1"><a href="logistic-regression.html#cb455-1" tabindex="-1"></a><span class="co"># create data frame of new learner</span></span>
<span id="cb455-2"><a href="logistic-regression.html#cb455-2" tabindex="-1"></a>new_learner <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb455-3"><a href="logistic-regression.html#cb455-3" tabindex="-1"></a>  <span class="at">age =</span> <span class="dv">15</span>,</span>
<span id="cb455-4"><a href="logistic-regression.html#cb455-4" tabindex="-1"></a>  <span class="at">sex =</span> <span class="st">&quot;Male&quot;</span>,</span>
<span id="cb455-5"><a href="logistic-regression.html#cb455-5" tabindex="-1"></a>  <span class="at">books =</span> <span class="st">&quot;No&quot;</span></span>
<span id="cb455-6"><a href="logistic-regression.html#cb455-6" tabindex="-1"></a>)</span>
<span id="cb455-7"><a href="logistic-regression.html#cb455-7" tabindex="-1"></a></span>
<span id="cb455-8"><a href="logistic-regression.html#cb455-8" tabindex="-1"></a><span class="co"># predict probability to meet MPL both</span></span>
<span id="cb455-9"><a href="logistic-regression.html#cb455-9" tabindex="-1"></a>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(m3,</span>
<span id="cb455-10"><a href="logistic-regression.html#cb455-10" tabindex="-1"></a>  <span class="at">newdata =</span> new_learner,</span>
<span id="cb455-11"><a href="logistic-regression.html#cb455-11" tabindex="-1"></a>  <span class="at">type    =</span> <span class="st">&quot;link&quot;</span></span>
<span id="cb455-12"><a href="logistic-regression.html#cb455-12" tabindex="-1"></a>)</span>
<span id="cb455-13"><a href="logistic-regression.html#cb455-13" tabindex="-1"></a></span>
<span id="cb455-14"><a href="logistic-regression.html#cb455-14" tabindex="-1"></a><span class="co"># print results</span></span>
<span id="cb455-15"><a href="logistic-regression.html#cb455-15" tabindex="-1"></a>new_learner<span class="sc">$</span>probabilities <span class="ot">&lt;-</span> <span class="fu">plogis</span>(pred)</span>
<span id="cb455-16"><a href="logistic-regression.html#cb455-16" tabindex="-1"></a></span>
<span id="cb455-17"><a href="logistic-regression.html#cb455-17" tabindex="-1"></a>new_learner</span></code></pre></div>
<pre><code>##   age  sex books probabilities
## 1  15 Male    No         0.564</code></pre>
<p>If we <em>trust</em> our logistic regression model, the probability that this new child meets MPL for both reading and math is predicted to be <span class="math inline">\(56.5\%\)</span>.</p>
<p>We can also visualize the effect of <code>age</code> and <code>books</code> on the predicted probability of meeting MPL in <span class="citation">@fig-vistwo</span>.</p>
<div class="sourceCode" id="cb457"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb457-1"><a href="logistic-regression.html#cb457-1" tabindex="-1"></a><span class="fu">plot_model</span>(m3,</span>
<span id="cb457-2"><a href="logistic-regression.html#cb457-2" tabindex="-1"></a>  <span class="at">type =</span> <span class="st">&quot;pred&quot;</span>,</span>
<span id="cb457-3"><a href="logistic-regression.html#cb457-3" tabindex="-1"></a>  <span class="at">terms =</span> <span class="fu">c</span>(<span class="st">&quot;age&quot;</span>, <span class="st">&quot;books&quot;</span>)</span>
<span id="cb457-4"><a href="logistic-regression.html#cb457-4" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb457-5"><a href="logistic-regression.html#cb457-5" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb457-6"><a href="logistic-regression.html#cb457-6" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Prob(MPL on both reading and math)&quot;</span>,</span>
<span id="cb457-7"><a href="logistic-regression.html#cb457-7" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Child&#39;s Age in Years&quot;</span>,</span>
<span id="cb457-8"><a href="logistic-regression.html#cb457-8" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Predicted probabilities of MPL with Age and Books&quot;</span></span>
<span id="cb457-9"><a href="logistic-regression.html#cb457-9" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb457-10"><a href="logistic-regression.html#cb457-10" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code></pre></div>
<p><img src="figs/fig-vistwo-1.png" width="672" /></p>
<p>These plots confirm that:</p>
<ul>
<li><p>There is a positive relationship between the child’s age and meeting MPL for both maths and reading.</p></li>
<li><p>The odds of meeting MPL for both maths and reading is higher for children who bring back home study material from the school library for reading. This observation intensifies as the child’s age increases.</p></li>
</ul>
</div>
<div id="interaction" class="section level2 hasAnchor" number="12.6">
<h2><span class="header-section-number">12.6</span> Interaction<a href="logistic-regression.html#interaction" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In the last section, we never considered potential interaction effects. In a regression model, interaction occurs when the relationship between a predictor and the outcome depends on the value or the level taken by another predictor. On the contrary, if the relationship between a predictor and the outcome remains unchanged no matter the value taken by another predictor, we cannot conclude that there is an interaction effect.</p>
<p>In our case, there would be an interaction if the relationship between the child’s <code>age</code> and MPL for both maths and reading depends on the <code>sex</code> predictor. There would be an interaction, for instance, if the relationship between the child’s <code>age</code> and MPL for both maths and reading was positive for female children, and negative for male children, or vice versa. Or if the relationship between the child’s <code>age</code> and MPL for both maths and reading was much stronger or much weaker for female children than for male children.</p>
<p>Let us see if there is any interaction between <code>age</code> and <code>sex</code>, and more importantly, whether or not this interaction is significant:</p>
<div class="sourceCode" id="cb458"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb458-1"><a href="logistic-regression.html#cb458-1" tabindex="-1"></a><span class="co"># save model with interaction</span></span>
<span id="cb458-2"><a href="logistic-regression.html#cb458-2" tabindex="-1"></a>m4_inter <span class="ot">&lt;-</span> <span class="fu">svyglm</span>(mpl_both <span class="sc">~</span> age <span class="sc">+</span> sex <span class="sc">+</span> books <span class="sc">+</span> sex <span class="sc">*</span> age,</span>
<span id="cb458-3"><a href="logistic-regression.html#cb458-3" tabindex="-1"></a>  <span class="at">family =</span> quasibinomial,</span>
<span id="cb458-4"><a href="logistic-regression.html#cb458-4" tabindex="-1"></a>  <span class="at">design =</span> des,</span>
<span id="cb458-5"><a href="logistic-regression.html#cb458-5" tabindex="-1"></a>  <span class="at">na.action =</span> na.omit</span>
<span id="cb458-6"><a href="logistic-regression.html#cb458-6" tabindex="-1"></a>)</span>
<span id="cb458-7"><a href="logistic-regression.html#cb458-7" tabindex="-1"></a></span>
<span id="cb458-8"><a href="logistic-regression.html#cb458-8" tabindex="-1"></a>m4_inter <span class="sc">|&gt;</span></span>
<span id="cb458-9"><a href="logistic-regression.html#cb458-9" tabindex="-1"></a>  <span class="fu">tidy</span>()</span></code></pre></div>
<pre><code>## # A tibble: 5 × 5
##   term        estimate std.error statistic  p.value
##   &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1 (Intercept)  -5.85      0.242     -24.2  7.96e-59
## 2 age           0.416     0.0195     21.3  2.28e-51
## 3 sexMale       0.698     0.277       2.52 1.27e- 2
## 4 booksYes      0.391     0.105       3.74 2.44e- 4
## 5 age:sexMale  -0.0621    0.0234     -2.65 8.71e- 3</code></pre>
<div id="interpretation-of-age-sex-and-the-agesex-interaction" class="section level3 hasAnchor" number="12.6.1">
<h3><span class="header-section-number">12.6.1</span> Interpretation of age, sex, and the age*sex interaction<a href="logistic-regression.html#interpretation-of-age-sex-and-the-agesex-interaction" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><code>age</code> is positively associated with MPL (<span class="math inline">\(\beta_{age} = 0.416\)</span>). For the reference group (Females), this corresponds to an odds ratio (OR) of <span class="math inline">\(1.52\)</span> per one-year increase in <code>age</code> (OR $ = e^{0.416} = 1.514$), holding other predictors constant.</p>
<p>The age-by-sex interaction is statistically significant (<span class="math inline">\(\beta_{int} = -0.062\)</span>, <em>p</em>-value<span class="math inline">\(=0.0087\)</span>), which indicates that the <code>age</code> effect differs by <code>sex</code>. Specifically, the age slope for males equals <span class="math inline">\(\beta_{age}+ \beta_{int} = 0.354\)</span>, which corresponds to an OR of <span class="math inline">\(1.42\)</span> per year (<span class="math inline">\(e^{0.354} = 1.425\)</span>). Equivalently, the male-to-female odds ratio changes multiplicatively by <span class="math inline">\(e^{\beta_{int}} = 0.94\)</span> per additional year of age (<span class="math inline">\(\approx 5,7\%\)</span> decrease per year), which implies that the relative male-female difference diminishes with increasing age.</p>
<p>Importantly, in the presence of an interaction, the main-effect coefficient for sex (<span class="math inline">\(\beta_{sexMale} = 0,70\)</span>) represents the male-female contrast when <code>age</code> is <span class="math inline">\(0\)</span> years old. Consequently, <span class="math inline">\(\beta_{sexMale}\)</span> should not be interpreted as an average sex effect across the observed age range. Next, let us visualize the <code>age</code>* <code>sex</code> interaction in <span class="citation">@fig-visthree</span>.</p>
<div class="sourceCode" id="cb460"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb460-1"><a href="logistic-regression.html#cb460-1" tabindex="-1"></a><span class="fu">plot_model</span>(m4_inter,</span>
<span id="cb460-2"><a href="logistic-regression.html#cb460-2" tabindex="-1"></a>  <span class="at">type =</span> <span class="st">&quot;pred&quot;</span>,</span>
<span id="cb460-3"><a href="logistic-regression.html#cb460-3" tabindex="-1"></a>  <span class="at">terms =</span> <span class="fu">c</span>(<span class="st">&quot;age&quot;</span>, <span class="st">&quot;sex&quot;</span>)</span>
<span id="cb460-4"><a href="logistic-regression.html#cb460-4" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb460-5"><a href="logistic-regression.html#cb460-5" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb460-6"><a href="logistic-regression.html#cb460-6" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Prob(MPL on both reading and math)&quot;</span>,</span>
<span id="cb460-7"><a href="logistic-regression.html#cb460-7" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Child&#39;s Age in Years&quot;</span>,</span>
<span id="cb460-8"><a href="logistic-regression.html#cb460-8" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;&quot;</span></span>
<span id="cb460-9"><a href="logistic-regression.html#cb460-9" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb460-10"><a href="logistic-regression.html#cb460-10" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:fig-visthree"></span>
<img src="figs/fig-visthree-1.png" alt="Predicted probability of MPL as a function of age, stratified by sex, from a logistic regression including an age×sex interaction (bands denote 95% confidence intervals). Predictions are computed with other predictors held constant (e.g., `books` fixed at its reference level)." width="672" />
<p class="caption">
Figure 12.3: Predicted probability of MPL as a function of age, stratified by sex, from a logistic regression including an age×sex interaction (bands denote 95% confidence intervals). Predictions are computed with other predictors held constant (e.g., <code>books</code> fixed at its reference level).
</p>
</div>
<p>Predicted probabilities from the interaction model increase with <code>age</code> for both sexes, which is consistent with the positive <code>age</code> coefficient. However, due to the negative <code>age</code>*<code>sex</code> interaction, the increase is steeper for females than for males, which leads to an age-dependent sex difference and a cross-over in the predicted curves around ~ 11 years. Confidence bands widen at the extremes of age, which reflects increased uncertainty where data is sparser.</p>
<p>Note: When plotting predicted probabilities as a function of <code>age</code> and <code>sex</code>, other predictors (i.e., <code>books</code>) are held constant.</p>
</div>
</div>
<div id="reporting-results-1" class="section level2 hasAnchor" number="12.7">
<h2><span class="header-section-number">12.7</span> Reporting Results<a href="logistic-regression.html#reporting-results-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>As we have seen before, odds ratios are useful when reporting results of binary logistic regressions.</p>
<p>Computing these odds ratios together with the confidence intervals is not particularly difficult. However, presenting them in a table for a publication or a report can quickly become time consuming, in particular if you have many models and many independent variables.</p>
<p>Luckily, there are two packages which saved me a lot of time and which I use almost every time I need to report results of a logistic regression. It is <code>knitr()</code> and <code>kableExtra()</code>. Here is an example with one of the models we have built previously:</p>
<div class="sourceCode" id="cb461"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb461-1"><a href="logistic-regression.html#cb461-1" tabindex="-1"></a><span class="co"># load the package</span></span>
<span id="cb461-2"><a href="logistic-regression.html#cb461-2" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb461-3"><a href="logistic-regression.html#cb461-3" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb461-4"><a href="logistic-regression.html#cb461-4" tabindex="-1"></a></span>
<span id="cb461-5"><a href="logistic-regression.html#cb461-5" tabindex="-1"></a><span class="co"># print table of results</span></span>
<span id="cb461-6"><a href="logistic-regression.html#cb461-6" tabindex="-1"></a>tab <span class="ot">&lt;-</span> <span class="fu">summary</span>(m4_inter)<span class="sc">$</span>coefficients <span class="sc">|&gt;</span></span>
<span id="cb461-7"><a href="logistic-regression.html#cb461-7" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">|&gt;</span></span>
<span id="cb461-8"><a href="logistic-regression.html#cb461-8" tabindex="-1"></a>  tibble<span class="sc">::</span><span class="fu">rownames_to_column</span>(<span class="st">&quot;term&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb461-9"><a href="logistic-regression.html#cb461-9" tabindex="-1"></a>  <span class="fu">rename</span>(</span>
<span id="cb461-10"><a href="logistic-regression.html#cb461-10" tabindex="-1"></a>    <span class="at">estimate  =</span> Estimate,</span>
<span id="cb461-11"><a href="logistic-regression.html#cb461-11" tabindex="-1"></a>    <span class="at">std.error =</span> <span class="st">`</span><span class="at">Std. Error</span><span class="st">`</span>,</span>
<span id="cb461-12"><a href="logistic-regression.html#cb461-12" tabindex="-1"></a>    <span class="at">statistic =</span> <span class="st">`</span><span class="at">t value</span><span class="st">`</span>,</span>
<span id="cb461-13"><a href="logistic-regression.html#cb461-13" tabindex="-1"></a>    <span class="at">p_value   =</span> <span class="st">`</span><span class="at">Pr(&gt;|t|)</span><span class="st">`</span></span>
<span id="cb461-14"><a href="logistic-regression.html#cb461-14" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb461-15"><a href="logistic-regression.html#cb461-15" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb461-16"><a href="logistic-regression.html#cb461-16" tabindex="-1"></a>    <span class="at">OR =</span> <span class="fu">exp</span>(estimate),</span>
<span id="cb461-17"><a href="logistic-regression.html#cb461-17" tabindex="-1"></a>    <span class="at">OR_low =</span> <span class="fu">exp</span>(estimate <span class="sc">-</span> <span class="fl">1.96</span> <span class="sc">*</span> std.error),</span>
<span id="cb461-18"><a href="logistic-regression.html#cb461-18" tabindex="-1"></a>    <span class="at">OR_high =</span> <span class="fu">exp</span>(estimate <span class="sc">+</span> <span class="fl">1.96</span> <span class="sc">*</span> std.error),</span>
<span id="cb461-19"><a href="logistic-regression.html#cb461-19" tabindex="-1"></a>    <span class="at">p_value =</span> <span class="fu">ifelse</span>(p_value <span class="sc">&lt;</span> <span class="fl">0.001</span>, <span class="st">&quot;&lt;0.001&quot;</span>, <span class="fu">sprintf</span>(<span class="st">&quot;%.3f&quot;</span>, p_value)),</span>
<span id="cb461-20"><a href="logistic-regression.html#cb461-20" tabindex="-1"></a>    <span class="st">`</span><span class="at">OR (95% CI)</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">sprintf</span>(<span class="st">&quot;%.2f (%.2f, %.2f)&quot;</span>, OR, OR_low, OR_high)</span>
<span id="cb461-21"><a href="logistic-regression.html#cb461-21" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb461-22"><a href="logistic-regression.html#cb461-22" tabindex="-1"></a>  <span class="fu">select</span>(term, estimate, std.error, statistic, <span class="st">`</span><span class="at">OR (95% CI)</span><span class="st">`</span>, p_value)</span>
<span id="cb461-23"><a href="logistic-regression.html#cb461-23" tabindex="-1"></a></span>
<span id="cb461-24"><a href="logistic-regression.html#cb461-24" tabindex="-1"></a></span>
<span id="cb461-25"><a href="logistic-regression.html#cb461-25" tabindex="-1"></a><span class="co"># print the results</span></span>
<span id="cb461-26"><a href="logistic-regression.html#cb461-26" tabindex="-1"></a></span>
<span id="cb461-27"><a href="logistic-regression.html#cb461-27" tabindex="-1"></a><span class="fu">kable</span>(</span>
<span id="cb461-28"><a href="logistic-regression.html#cb461-28" tabindex="-1"></a>  tab,</span>
<span id="cb461-29"><a href="logistic-regression.html#cb461-29" tabindex="-1"></a>  <span class="at">booktabs =</span> <span class="cn">TRUE</span>,</span>
<span id="cb461-30"><a href="logistic-regression.html#cb461-30" tabindex="-1"></a>  <span class="at">align =</span> <span class="fu">c</span>(<span class="st">&quot;l&quot;</span>, <span class="st">&quot;r&quot;</span>, <span class="st">&quot;r&quot;</span>, <span class="st">&quot;r&quot;</span>, <span class="st">&quot;r&quot;</span>, <span class="st">&quot;r&quot;</span>),</span>
<span id="cb461-31"><a href="logistic-regression.html#cb461-31" tabindex="-1"></a>  <span class="at">digits =</span> <span class="fu">c</span>(<span class="cn">NA</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">2</span>, <span class="cn">NA</span>, <span class="cn">NA</span>),</span>
<span id="cb461-32"><a href="logistic-regression.html#cb461-32" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">&quot;Survey-weighted logistic regression (svyglm) results&quot;</span></span>
<span id="cb461-33"><a href="logistic-regression.html#cb461-33" tabindex="-1"></a>) <span class="sc">|&gt;</span></span>
<span id="cb461-34"><a href="logistic-regression.html#cb461-34" tabindex="-1"></a>  <span class="fu">kable_styling</span>(</span>
<span id="cb461-35"><a href="logistic-regression.html#cb461-35" tabindex="-1"></a>    <span class="at">full_width =</span> <span class="cn">FALSE</span>,</span>
<span id="cb461-36"><a href="logistic-regression.html#cb461-36" tabindex="-1"></a>    <span class="at">position =</span> <span class="st">&quot;left&quot;</span>,</span>
<span id="cb461-37"><a href="logistic-regression.html#cb461-37" tabindex="-1"></a>    <span class="at">latex_options =</span> <span class="fu">c</span>(<span class="st">&quot;hold_position&quot;</span>) <span class="co"># nice for PDF/Quarto/Rmd</span></span>
<span id="cb461-38"><a href="logistic-regression.html#cb461-38" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb461-39"><a href="logistic-regression.html#cb461-39" tabindex="-1"></a>  <span class="fu">add_header_above</span>(<span class="fu">c</span>(<span class="st">&quot; &quot;</span> <span class="ot">=</span> <span class="dv">1</span>, <span class="st">&quot;Coefficient&quot;</span> <span class="ot">=</span> <span class="dv">3</span>, <span class="st">&quot;Odds ratio&quot;</span> <span class="ot">=</span> <span class="dv">1</span>, <span class="st">&quot; &quot;</span> <span class="ot">=</span> <span class="dv">1</span>)) <span class="sc">|&gt;</span></span>
<span id="cb461-40"><a href="logistic-regression.html#cb461-40" tabindex="-1"></a>  <span class="fu">column_spec</span>(<span class="dv">1</span>, <span class="at">bold =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<table class="table" style="width: auto !important; ">
<caption>
(#tab:reporting results)(#tab:reporting results)Survey-weighted logistic regression (svyglm) results
</caption>
<thead>
<tr>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="1">
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="3">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Coefficient
</div>
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="1">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Odds ratio
</div>
</th>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="1">
</th>
</tr>
<tr>
<th style="text-align:left;">
term
</th>
<th style="text-align:right;">
estimate
</th>
<th style="text-align:right;">
std.error
</th>
<th style="text-align:right;">
statistic
</th>
<th style="text-align:right;">
OR (95% CI)
</th>
<th style="text-align:right;">
p_value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;font-weight: bold;">
(Intercept)
</td>
<td style="text-align:right;">
-5.851
</td>
<td style="text-align:right;">
0.242
</td>
<td style="text-align:right;">
-24.16
</td>
<td style="text-align:right;">
0.00 (0.00, 0.00)
</td>
<td style="text-align:right;">
&lt;0.001
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
age
</td>
<td style="text-align:right;">
0.416
</td>
<td style="text-align:right;">
0.020
</td>
<td style="text-align:right;">
21.28
</td>
<td style="text-align:right;">
1.52 (1.46, 1.57)
</td>
<td style="text-align:right;">
&lt;0.001
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
sexMale
</td>
<td style="text-align:right;">
0.698
</td>
<td style="text-align:right;">
0.277
</td>
<td style="text-align:right;">
2.52
</td>
<td style="text-align:right;">
2.01 (1.17, 3.46)
</td>
<td style="text-align:right;">
0.013
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
booksYes
</td>
<td style="text-align:right;">
0.391
</td>
<td style="text-align:right;">
0.105
</td>
<td style="text-align:right;">
3.74
</td>
<td style="text-align:right;">
1.48 (1.20, 1.81)
</td>
<td style="text-align:right;">
&lt;0.001
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
age:sexMale
</td>
<td style="text-align:right;">
-0.062
</td>
<td style="text-align:right;">
0.023
</td>
<td style="text-align:right;">
-2.65
</td>
<td style="text-align:right;">
0.94 (0.90, 0.98)
</td>
<td style="text-align:right;">
0.009
</td>
</tr>
</tbody>
</table>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="multiple-linear-regression.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/DataFirst-Courses/Introduction-To-Survey-Data-Analysis-using-R/edit/main/11-logisticreg.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": "https://github.com/DataFirst-Courses/Introduction-To-Survey-Data-Analysis-using-R/blob/main/11-logisticreg.Rmd",
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
